### ISSUE TITLE
Case-sensitivity in "Handle" part of URL

### ISSUE THREAD

**Issue by harununal** [monocash/iban.im#16]
This project for remember URL easily. I think case-sensivity is unnecessary. 

https://iban.im/harununal/HALKBANK => true
https://iban.im/harununal/halkbank => false
https://iban.im/harUNUNAL/HALKBANK => true

**Comment by enesacikoglu** [comment]
Hello,
I can take this,Could you describe the detail of the problem and requirement please ?
Thanks

**Comment by hmert** [comment]
@enesacikoglu User and IBAN handle should be stored as lowercase both frontend and backend.
